site_name: Megafactory
theme:
  logo: assets/logo.png
  favicon: assets/logo.png
  name: material
  font:
    text: Inter
  palette:
    scheme: slate
    primary: custom
  features:
    - navigation.path
    - navigation.indexes 
    - content.code.copy
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
markdown_extensions:
  - pymdownx.details
  - admonition
  - pymdownx.superfences
extra_css:
  - stylesheets/extra.css